# Generated by Django 5.1.1 on 2025-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0004_users_created_at_users_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
