# Generated by Django 5.1.1 on 2025-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0005_roles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
