# Generated by Django 5.1.1 on 2025-01-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
