# Generated by Django 5.1.1 on 2025-01-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0013_rename_comments_review_exta_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='exta_comments',
            new_name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
